import type { ISecretRoom } from "@/libs/types";
import type { mapNamesUnion } from "@/libs/mapsParams";

// 密室位置配置
// 每个地图的密室位置配置
type SecretRoomConfig = {
  [key in mapNamesUnion]?: ISecretRoom[];
};

const secretRooms: SecretRoomConfig = {
  // 艾伦格地图密室位置
  erangel: [
    {
      id: "erangel-sr-001",
      position: { x: 135.8, y: 178.4 },
      name: "密室 #1",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "erangel-sr-002",
      position: { x: 458.9, y: 435.7 },
      name: "密室 #2",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "erangel-sr-003",
      position: { x: 255.2, y: 217.6 },
      name: "密室 #3",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "erangel-sr-004",
      position: { x: 558.6, y: 662.6 },
      name: "密室 #4",
      description: "",
      lootLevel: 1,
      keyRequired: false,
    },
    {
      id: "erangel-sr-005",
      position: { x: 296.6, y: 369.2 },
      name: "密室 #5",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "erangel-sr-006",
      position: { x: 325.2, y: 660 },
      name: "密室 #6",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "erangel-sr-007",
      position: { x: 642.6, y: 204.4 },
      name: "密室 #7",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "erangel-sr-008",
      position: { x: 124.4, y: 544.4 },
      name: "密室 #8",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "erangel-sr-009",
      position: { x: 406.2, y: 193.8 },
      name: "密室 #9",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "erangel-sr-010",
      position: { x: 269.6, y: 507.3 },
      name: "密室 #10",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "erangel-sr-011",
      position: { x: 538.2, y: 337.2 },
      name: "密室 #11",
      description: "",
      lootLevel: 1,
      keyRequired: false,
    },
    {
      id: "erangel-sr-012",
      position: { x: 433.2, y: 582.8 },
      name: "密室 #12",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "erangel-sr-013",
      position: { x: 146, y: 348.6 },
      name: "密室 #13",
      description: "",
      lootLevel: 1,
      keyRequired: false,
    },
    {
      id: "erangel-sr-014",
      position: { x: 665.2, y: 482 },
      name: "密室 #14",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "erangel-sr-015",
      position: { x: 504.6, y: 65.5 },
      name: "密室 #15",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
  ],

  //维寒迪地图密室位置
  vikendi: [
    {
      id: "vikendi-sr-001",
      position: { x: 270, y: 155 },
      name: "密室 #1",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "vikendi-sr-002",
      position: { x: 532, y: 130 },
      name: "密室 #2",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "vikendi-sr-003",
      position: { x: 614, y: 242 },
      name: "密室 #3",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "vikendi-sr-004",
      position: { x: 673, y: 382 },
      name: "密室 #4",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "vikendi-sr-005",
      position: { x: 597, y: 577 },
      name: "密室 #5",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "vikendi-sr-006",
      position: { x: 463, y: 487 },
      name: "密室 #6",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "vikendi-sr-007",
      position: { x: 389, y: 643 },
      name: "密室 #7",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "vikendi-sr-008",
      position: { x: 234, y: 553 },
      name: "密室 #8",
      description: "",
      lootLevel: 1,
      keyRequired: false,
    },
    {
      id: "vikendi-sr-009",
      position: { x: 137, y: 377 },
      name: "密室 #9",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "vikendi-sr-010",
      position: { x: 404, y: 316 },
      name: "密室 #10",
      description: "",
      lootLevel: 1,
      keyRequired: false,
    },
  ],

  // 泰戈地图密室位置
  taego: [
    {
      id: "taego-sr-001",
      position: { x: 137.2, y: 117 },
      name: "密室 #1",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "taego-sr-002",
      position: { x: 252.2, y: 132.3 },
      name: "密室 #2",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "taego-sr-003",
      position: { x: 351, y: 193.4 },
      name: "密室 #3",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "taego-sr-004",
      position: { x: 474.2, y: 168.5 },
      name: "密室 #4",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "taego-sr-005",
      position: { x: 678, y: 204 },
      name: "密室 #5",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "taego-sr-006",
      position: { x: 696.4, y: 330 },
      name: "密室 #6",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "taego-sr-007",
      position: { x: 592.8, y: 379.6 },
      name: "密室 #7",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "taego-sr-008",
      position: { x: 629.4, y: 546.8 },
      name: "密室 #8",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "taego-sr-009",
      position: { x: 624, y: 705 },
      name: "密室 #9",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "taego-sr-010",
      position: { x: 487, y: 629.6 },
      name: "密室 #10",
      description: "",
      lootLevel: 1,
      keyRequired: false,
    },
    {
      id: "taego-sr-011",
      position: { x: 434, y: 487.4 },
      name: "密室 #11",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "taego-sr-012",
      position: { x: 238, y: 633 },
      name: "密室 #12",
      description: "",
      lootLevel: 1,
      keyRequired: false,
    },
    {
      id: "taego-sr-013",
      position: { x: 95, y: 514 },
      name: "密室 #13",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
    {
      id: "taego-sr-014",
      position: { x: 100, y: 334 },
      name: "密室 #14",
      description: "",
      lootLevel: 3,
      keyRequired: true,
    },
    {
      id: "taego-sr-015",
      position: { x: 123.6, y: 265 },
      name: "密室 #15",
      description: "",
      lootLevel: 2,
      keyRequired: true,
    },
  ],
};

export default secretRooms;
